# Arquivo de configuração Railway simplificado para máxima compatibilidade

[build]
# Usar Nixpacks para construir o projeto Node.js
builder = "nixpacks"
# Comando para construir o projeto
buildCommand = "npm run build"

[deploy]
# Usar o servidor estático mais simples e robusto
startCommand = "NODE_ENV=production node static-server.js"
# Desativar completamente o healthcheck que tem causado problemas
healthcheckEnabled = false
# Política de reinicialização em caso de falha
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10