[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100

[phases.setup]
nixPkgs = ["nodejs", "postgresql"]

[[hooks]]
type = "build"
command = "npm run db:push"