[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
# Configuração para usar o script personalizado de inicialização
startCommand = "node start.js"
healthcheckPath = "/health"
healthcheckTimeout = 90

[nixpacks]
start = "node start.js"