# Arquivo de configuração Railway totalmente simplificado
# Desativa completamente o healthcheck que tem causado problemas

[deploy]
healthcheckEnabled = false
restartPolicyType = "on_failure" 
restartPolicyMaxRetries = 10

# Definir o comando de inicialização para usar NODE_ENV=production
startCommand = "NODE_ENV=production node dist/index.js"